version: '3.9'

services:
  db: 
    restart: on-failure
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<YourStrong!Passw0rd>
      - MSSQL_PID=Express
    ports: 
      - 1433:1433

  spice:
    image: ${DOCKER_REGISTRY-}spice
    restart: always
    build:
      context: .
      dockerfile: Spice/Dockerfile
    environment:
      - DB_SERVER=db
      - DB_PORT=1433
      - DB_DATA_BASE=Spice
      - DB_USER=SA
      - DB_PASSWORD=<YourStrong!Passw0rd>
      - DB_INTEGRATED_SECURITY=False
      - DB_PERSIST_SECURITY=False
    depends_on:
      - db
#   ports:
#        - 8080:80
#        - 8081:443