version: '3.9'

services:
  db: 
    restart: on-failure
    image: postgres
#    networks:
#        frontend:
#            ipv4_address: 172.20.0.3
    environment:
      - POSTGRES_PASSWORD=<YourStrong!Passw0rd>
      - POSTGRES_USER=postgres
    ports: 
      - 5432:5432

  spice:
    image: ${DOCKER_REGISTRY-}spice
    restart: always
    build:
      context: .
      dockerfile: Spice/Dockerfile
    env_file: .env
    depends_on:
      - db

#    networks:
#        frontend:
#            ipv4_address: 172.20.0.2
#    environment:
#      - DB_PROVIDER=postgres
#      - DB_SERVER=db
##      - DB_SERVER=172.20.0.3
#      - DB_PORT=5432
#      - DB_DATA_BASE=Spice
#      - DB_USER=postgres
#      - DB_PASSWORD=<YourStrong!Passw0rd>
#      - DB_INTEGRATED_SECURITY=False
#      - DB_PERSIST_SECURITY=False

#networks:
#  frontend:
#    ipam:
#        config:
#            - subnet: 172.20.0.0/24

#   ports:
#        - 8080:80
#        - 8081:443